<?php

//use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
//use Drupal\node\Entity\NodeType;
//use Drupal\node\NodeInterface;
use Drupal\imagemagick\ImagemagickExecArguments;

/**
 * @file
 * Main file for custom hooks and functions.
 */

/**
 * Implements hook_theme().
 */
function blog_theme($existing, $type, $theme, $path) {
  return [
    'blog_previous_next' => [
      'variables' => [
        'entity' => NULL,
      ],
      'file' => 'blog.theme.inc',
      'pattern' => 'blog_previous_next__',
    ],
  ];
}

///**
// * Implements hook_entity_extra_field_info().
// */
//function blog_entity_extra_field_info(): array {
//  $extra = [];
//
//  foreach (NodeType::loadMultiple() as $bundle) {
//    $extra['node'][$bundle->id()]['display']['previous_next'] = [
//      'label' => t('Button to previous and next entity'),
//      'weight' => 100,
//      'visible' => FALSE,
//    ];
//  }
//
//  return $extra;
//}
//
///**
// * Implements hook_ENTITY_TYPE_view().
// */
//function blog_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display) {
//  if ($display->getComponent('previous_next')) {
//    $build['previous_next'] = [
//      '#theme' => 'blog_previous_next',
//      '#entity' => $node,
//    ];
//  }
//}

/**
 * Implements hook_imagemagick_arguments_alter().
 */
function blog_imagemagick_arguments_alter(ImagemagickExecArguments $arguments, $command) {
  $arguments->add('-sampling-factor 4:2:0')
    ->add('-interlace Plane')
    ->add('-strip');
}
